help=com.taobao.arthas.core.command.basic.HelpCommand
cls=com.taobao.arthas.core.command.basic.CLSCommand
dashboard=com.taobao.arthas.core.command.monitor200.DashboardCommand
trace=com.taobao.arthas.core.command.monitor200.TraceCommand
stack=com.taobao.arthas.core.command.monitor200.StackCommand
watch=com.taobao.arthas.core.command.monitor200.WatchCommand
monitor=com.taobao.arthas.core.command.monitor200.MonitorCommand
tt=com.taobao.arthas.core.command.monitor200.TimeTunnelCommand
repeat=com.taobao.arthas.core.command.monitor200.TimeTunnelRepeatCommand
ognl=com.taobao.arthas.core.command.ognl.OgnlCommand
memory=com.taobao.arthas.core.command.monitor200.MemoryCommand
heapdump=com.taobao.arthas.core.command.basic.HeapDumpCommand
sysprop=com.taobao.arthas.core.command.basic.SysPropCommand
sysenv=com.taobao.arthas.core.command.basic.SysEnvCommand
vmoption=com.taobao.arthas.core.command.basic.VMOptionCommand
jad=com.taobao.arthas.core.command.basic.JadCommand
mc=com.taobao.arthas.core.command.basic.McCommand
redefine=com.taobao.arthas.core.command.basic.RedefineCommand
classloader=com.taobao.arthas.core.command.classloader.ClassLoaderCommand
logger=com.taobao.arthas.core.command.logger.LoggerCommand

# ?? ????????????
logstat=com.taobao.arthas.core.command.monitor200.LogstatCommand
mvn clean package -DskipTests
